package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name="person"
    ,catalog="nighthawk_interteh"
)
public class Person  implements java.io.Serializable {


     private Integer idPerson;
     private Subcontractor subcontractor;
     private String personName;
     private String personAddress;
     private Integer personPhoneNumber;

    public Person() {
    }

	
    public Person(Subcontractor subcontractor) {
        this.subcontractor = subcontractor;
    }
    public Person(Subcontractor subcontractor, String personName, String personAddress, Integer personPhoneNumber) {
       this.subcontractor = subcontractor;
       this.personName = personName;
       this.personAddress = personAddress;
       this.personPhoneNumber = personPhoneNumber;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_Person", unique=true, nullable=false)
    public Integer getIdPerson() {
        return this.idPerson;
    }
    
    public void setIdPerson(Integer idPerson) {
        this.idPerson = idPerson;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_Subcontractor", nullable=false)
    public Subcontractor getSubcontractor() {
        return this.subcontractor;
    }
    
    public void setSubcontractor(Subcontractor subcontractor) {
        this.subcontractor = subcontractor;
    }

    
    @Column(name="Person_Name", length=45)
    public String getPersonName() {
        return this.personName;
    }
    
    public void setPersonName(String personName) {
        this.personName = personName;
    }

    
    @Column(name="Person_Address", length=45)
    public String getPersonAddress() {
        return this.personAddress;
    }
    
    public void setPersonAddress(String personAddress) {
        this.personAddress = personAddress;
    }

    
    @Column(name="Person_Phone_Number")
    public Integer getPersonPhoneNumber() {
        return this.personPhoneNumber;
    }
    
    public void setPersonPhoneNumber(Integer personPhoneNumber) {
        this.personPhoneNumber = personPhoneNumber;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 37 * hash + Objects.hashCode(this.idPerson);
        hash = 37 * hash + Objects.hashCode(this.personName);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Person other = (Person) obj;
        if (!Objects.equals(this.personName, other.personName)) {
            return false;
        }
        if (!Objects.equals(this.idPerson, other.idPerson)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Person{" + "idPerson=" + idPerson + ", subcontractor=" + subcontractor + ", personName=" + personName + ", personAddress=" + personAddress + ", personPhoneNumber=" + personPhoneNumber + '}';
    }




}


