package com.iucosoft.nighthawk_interteh_web_cms.dto;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.Objects;

/**
 * Filecontent generated by hbm2java
 */

public class FilecontentDTO    implements Serializable{


//     private Integer documentContentId;
//     private Filedocument filedocument;
//     private String fileContent;
     private Date lastUpdated;

    public FilecontentDTO() {
        
        
    }

    public Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.lastUpdated);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final FilecontentDTO other = (FilecontentDTO) obj;
        if (!Objects.equals(this.lastUpdated, other.lastUpdated)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "FilecontentDTO{" + "lastUpdated=" + lastUpdated + '}';
    }

	
}


