package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1

import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Administrator generated by hbm2java
 */
@Entity
@Table(name = "administrator",
        catalog = "nighthawk_interteh"
)
public class Administrator implements java.io.Serializable {

    private Integer idAdministrator;
    private NWUser user;
    private String administratorName;
    private String administratorEmail;

    public Administrator() {
    }

    public Administrator(Integer idAdministrator, NWUser user, String administratorName, String administratorEmail) {
        this.idAdministrator = idAdministrator;
        this.user = user;
        this.administratorName = administratorName;
        this.administratorEmail = administratorEmail;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)

    @Column(name = "ID_Administrator", unique = true, nullable = false)
    public Integer getIdAdministrator() {
        return this.idAdministrator;
    }

    public void setIdAdministrator(Integer idAdministrator) {
        this.idAdministrator = idAdministrator;
    }

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "User_ID", nullable = false)
    public NWUser getUser() {
        return this.user;
    }

    public void setUser(NWUser user) {
        this.user = user;
    }

    @Column(name = "Administrator_Name", length = 45)
    public String getAdministratorName() {
        return this.administratorName;
    }

    public void setAdministratorName(String administratorName) {
        this.administratorName = administratorName;
    }

    @Column(name = "Administrator_Email", length = 45)
    public String getAdministratorEmail() {
        return this.administratorEmail;
    }

    public void setAdministratorEmail(String administratorEmail) {
        this.administratorEmail = administratorEmail;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.idAdministrator);
        hash = 97 * hash + Objects.hashCode(this.user);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Administrator other = (Administrator) obj;
        if (!Objects.equals(this.idAdministrator, other.idAdministrator)) {
            return false;
        }
        if (!Objects.equals(this.user, other.user)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Administrator{" + "idAdministrator=" + idAdministrator + ", user=" + user + ", administratorName=" + administratorName + ", administratorEmail=" + administratorEmail + '}';
    }

}
