package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Filedocument generated by hbm2java
 */
@Entity
@Table(name = "filedocument",
         catalog = "nighthawk_interteh"
)
public class Filedocument implements java.io.Serializable {

    private Integer fileDocumentId;
    private Account account;
    private String fileName;
    private String fileExtenstion;
    private String documentContent;
//     private Set<Filecontent> filecontents = new HashSet<Filecontent>(0);

    public Filedocument() {
    }

    public Filedocument(Account account) {
        this.account = account;
    }

    public Filedocument(Account account, String fileName, String fileExtenstion, String documentContent) {
        this.account = account;
        this.fileName = fileName;
        this.fileExtenstion = fileExtenstion;
        this.documentContent = documentContent;
//       this.filecontents = filecontents;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "Document_ID", unique = true, nullable = false)
    public Integer getFileDocumentId() {
        return fileDocumentId;
    }

    public void setFileDocumentId(Integer fileDocumentId) {
        this.fileDocumentId = fileDocumentId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "Account_ID", nullable = false)
    public Account getAccount() {
        return this.account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    @Column(name = "File_Name", length = 45)
    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    @Column(name = "File_Extenstion", length = 45)
    public String getFileExtenstion() {
        return this.fileExtenstion;
    }

    public void setFileExtenstion(String fileExtenstion) {
        this.fileExtenstion = fileExtenstion;
    }

    @Column(name = "Document_Content", length = 45)
    public String getDocumentContent() {
        return this.documentContent;
    }

    public void setDocumentContent(String documentContent) {
        this.documentContent = documentContent;
    }

//@OneToMany(fetch=FetchType.EAGER, mappedBy="filedocument")
//    public Set<Filecontent> getFilecontents() {
//        return this.filecontents;
//    }
//    
//    public void setFilecontents(Set<Filecontent> filecontents) {
//        this.filecontents = filecontents;
//    }
    @Override
    public int hashCode() {
        int hash = 5;
        hash = 79 * hash + Objects.hashCode(this.fileDocumentId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Filedocument other = (Filedocument) obj;
        if (!Objects.equals(this.fileDocumentId, other.fileDocumentId)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Filedocument{" + "fileDocumentId=" + fileDocumentId + ", account=" + account + ", fileName=" + fileName + ", fileExtenstion=" + fileExtenstion + ", documentContent=" + documentContent + '}';
    }

}
