package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Filecontent generated by hbm2java
 */
@Entity
@Table(name="filecontent"
    ,catalog="nighthawk_interteh"
)
public class Filecontent  implements java.io.Serializable {


     private Integer documentContentId;
     private Filedocument filedocument;
     private String fileContent;
     private Date lastUpdated;

    public Filecontent() {
    }

	
    public Filecontent(Filedocument filedocument) {
        this.filedocument = filedocument;
    }
    public Filecontent(Filedocument filedocument, String fileContent, Date lastUpdated) {
       this.filedocument = filedocument;
       this.fileContent = fileContent;
       this.lastUpdated = lastUpdated;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Document_Content_ID", unique=true, nullable=false)
    public Integer getDocumentContentId() {
        return this.documentContentId;
    }
    
    public void setDocumentContentId(Integer documentContentId) {
        this.documentContentId = documentContentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Document_ID", nullable=false)
    public Filedocument getFiledocument() {
        return this.filedocument;
    }
    
    public void setFiledocument(Filedocument filedocument) {
        this.filedocument = filedocument;
    }

    
    @Column(name="File_Content", length=100)
    public String getFileContent() {
        return this.fileContent;
    }
    
    public void setFileContent(String fileContent) {
        this.fileContent = fileContent;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Last_Updated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 61 * hash + Objects.hashCode(this.documentContentId);
        hash = 61 * hash + Objects.hashCode(this.filedocument);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Filecontent other = (Filecontent) obj;
        if (!Objects.equals(this.documentContentId, other.documentContentId)) {
            return false;
        }
        if (!Objects.equals(this.filedocument, other.filedocument)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Filecontent{" + "documentContentId=" + documentContentId + ", filedocument=" + filedocument + ", fileContent=" + fileContent + ", lastUpdated=" + lastUpdated + '}';
    }




}


