package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Portofolio generated by hbm2java
 */
@Entity
@Table(name="portofolio"
    ,catalog="nighthawk_interteh"
)
public class Portofolio  implements java.io.Serializable {


     private Integer documentId;
     private Account account;
     private String fileName;
     private String fiileExtension;
     private String documentContent;

    public Portofolio() {
    }

	
    public Portofolio(Account account) {
        this.account = account;
    }
    public Portofolio(Account account, String fileName, String fiileExtension, String documentContent) {
       this.account = account;
       this.fileName = fileName;
       this.fiileExtension = fiileExtension;
       this.documentContent = documentContent;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Document_ID", unique=true, nullable=false)
    public Integer getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_Account", nullable=false)
    public Account getAccount() {
        return this.account;
    }
    
    public void setAccount(Account account) {
        this.account = account;
    }

    
    @Column(name="File_Name", length=45)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="Fiile_Extension", length=45)
    public String getFiileExtension() {
        return this.fiileExtension;
    }
    
    public void setFiileExtension(String fiileExtension) {
        this.fiileExtension = fiileExtension;
    }

    
    @Column(name="Document_Content", length=100)
    public String getDocumentContent() {
        return this.documentContent;
    }
    
    public void setDocumentContent(String documentContent) {
        this.documentContent = documentContent;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 71 * hash + Objects.hashCode(this.documentId);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Portofolio other = (Portofolio) obj;
        if (!Objects.equals(this.documentId, other.documentId)) {
            return false;
        }
        return true;
    }
    
    



    @Override
    public String toString() {
        return "Portofolio{" + "documentId=" + documentId + ", account=" + account + ", fileName=" + fileName + ", fiileExtension=" + fiileExtension + ", documentContent=" + documentContent + '}';
    }

   



}


