package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractProjectId generated by hbm2java
 */
@Embeddable
public class ContractProjectId  implements java.io.Serializable {


     private int contractId;
     private int projectId;

    public ContractProjectId() {
    }

    public ContractProjectId(int contractId, int projectId) {
       this.contractId = contractId;
       this.projectId = projectId;
    }
   


    @Column(name="Contract_ID", nullable=false)
    public int getContractId() {
        return this.contractId;
    }
    
    public void setContractId(int contractId) {
        this.contractId = contractId;
    }


    @Column(name="Project_ID", nullable=false)
    public int getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(int projectId) {
        this.projectId = projectId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContractProjectId) ) return false;
		 ContractProjectId castOther = ( ContractProjectId ) other; 
         
		 return (this.getContractId()==castOther.getContractId())
 && (this.getProjectId()==castOther.getProjectId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getContractId();
         result = 37 * result + this.getProjectId();
         return result;
   }   

    @Override
    public String toString() {
        return "ContractProjectId{" + "contractId=" + contractId + ", projectId=" + projectId + '}';
    }


}


