package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="nighthawk_interteh"
)
public class Account  implements java.io.Serializable {


     private Integer idAccount;
     private NWUser user;
     private int idPortofolio;
     private String projectsList;
     private String contractList;
     private Set<Portofolio> portofolios = new HashSet<Portofolio>(0);
     private Set<Project> projects = new HashSet<Project>(0);
     private Set<Filedocument> filedocuments = new HashSet<Filedocument>(0);

    public Account() {
    }

	
    public Account(NWUser user, int idPortofolio) {
        this.user = user;
        this.idPortofolio = idPortofolio;
    }
    public Account(NWUser user, int idPortofolio, String projectsList, String contractList, Set<Portofolio> portofolios, Set <Project> projects, Set<Filedocument> filedocuments) {
       this.user = user;
       this.idPortofolio = idPortofolio;
       this.projectsList = projectsList;
       this.contractList = contractList;
       this.portofolios = portofolios;
       this.projects = projects;
       this.filedocuments = filedocuments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_Account", unique=true, nullable=false)
    public Integer getIdAccount() {
        return this.idAccount;
    }
    
    public void setIdAccount(Integer idAccount) {
        this.idAccount = idAccount;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ID_User", nullable=false)
    public NWUser getUser() {
        return this.user;
    }
    
    public void setUser(NWUser user) {
        this.user = user;
    }

    
    @Column(name="ID_Portofolio", nullable=false)
    public int getIdPortofolio() {
        return this.idPortofolio;
    }
    
    public void setIdPortofolio(int idPortofolio) {
        this.idPortofolio = idPortofolio;
    }

    
    @Column(name="Projects_List", length=100)
    public String getProjectsList() {
        return this.projectsList;
    }
    
    public void setProjectsList(String projectsList) {
        this.projectsList = projectsList;
    }

    
    @Column(name="Contract_List", length=100)
    public String getContractList() {
        return this.contractList;
    }
    
    public void setContractList(String contractList) {
        this.contractList = contractList;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Portofolio> getPortofolios() {
        return this.portofolios;
    }
    
    public void setPortofolios(Set<Portofolio> portofolios) {
        this.portofolios = portofolios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Project> getProjects() {
        return this.projects;
    }
    
    public void setProjects(Set<Project> projects) {
        this.projects = projects;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Filedocument> getFiledocuments() {
        return this.filedocuments;
    }
    
    public void setFiledocuments(Set<Filedocument> filedocuments) {
        this.filedocuments = filedocuments;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.idAccount);
        hash = 17 * hash + Objects.hashCode(this.projects);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Account other = (Account) obj;
        if (!Objects.equals(this.idAccount, other.idAccount)) {
            return false;
        }
        if (!Objects.equals(this.projects, other.projects)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Account{" + "idAccount=" + idAccount + ", user=" + user + ", idPortofolio=" + idPortofolio + ", projectsList=" + projectsList + ", contractList=" + contractList + ", portofolios=" + portofolios + ", projects=" + projects + ", filedocuments=" + filedocuments + '}';
    }
    
    
    

    



}


