package com.iucosoft.nighthawk_interteh_service.entities;
// Generated 22-Jan-2022 16:56:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Employercompany generated by hbm2java
 */
@Entity
@Table(name="employercompany"
    ,catalog="nighthawk_interteh"
)
public class Employercompany  implements java.io.Serializable {


     private Integer idClientCompany;
     private String clientCompanyAddress;
     private String clientCompanyName;
     private String clientCompanyType;
     private String clientCompanyDescription;
     private Set<Contract> contracts = new HashSet<Contract>(0);

    public Employercompany() {
    }

    public Employercompany(String clientCompanyAddress, String clientCompanyName, String clientCompanyType, String clientCompanyDescription, Set<Contract> contracts) {
       this.clientCompanyAddress = clientCompanyAddress;
       this.clientCompanyName = clientCompanyName;
       this.clientCompanyType = clientCompanyType;
       this.clientCompanyDescription = clientCompanyDescription;
       this.contracts = contracts;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID_Client_Company", unique=true, nullable=false)
    public Integer getIdClientCompany() {
        return this.idClientCompany;
    }
    
    public void setIdClientCompany(Integer idClientCompany) {
        this.idClientCompany = idClientCompany;
    }

    
    @Column(name="Client_Company_Address", length=45)
    public String getClientCompanyAddress() {
        return this.clientCompanyAddress;
    }
    
    public void setClientCompanyAddress(String clientCompanyAddress) {
        this.clientCompanyAddress = clientCompanyAddress;
    }

    
    @Column(name="Client_Company_Name", length=45)
    public String getClientCompanyName() {
        return this.clientCompanyName;
    }
    
    public void setClientCompanyName(String clientCompanyName) {
        this.clientCompanyName = clientCompanyName;
    }

    
    @Column(name="Client_Company_Type", length=45)
    public String getClientCompanyType() {
        return this.clientCompanyType;
    }
    
    public void setClientCompanyType(String clientCompanyType) {
        this.clientCompanyType = clientCompanyType;
    }

    
    @Column(name="Client_Company_Description", length=45)
    public String getClientCompanyDescription() {
        return this.clientCompanyDescription;
    }
    
    public void setClientCompanyDescription(String clientCompanyDescription) {
        this.clientCompanyDescription = clientCompanyDescription;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employercompany")
    public Set<Contract> getContracts() {
        return this.contracts;
    }
    
    public void setContracts(Set<Contract> contracts) {
        this.contracts = contracts;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 97 * hash + Objects.hashCode(this.idClientCompany);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Employercompany other = (Employercompany) obj;
        if (!Objects.equals(this.idClientCompany, other.idClientCompany)) {
            return false;
        }
        return true;
    }
    
    
    

    @Override
    public String toString() {
        return "Employercompany{" + "idClientCompany=" + idClientCompany + ", clientCompanyAddress=" + clientCompanyAddress + ", clientCompanyName=" + clientCompanyName + ", clientCompanyType=" + clientCompanyType + ", clientCompanyDescription=" + clientCompanyDescription + '}';
    }




}


